{% set name = "miles-cpp" %}
{% set version = "0.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/mleszczynski-dev/miles-cpp.git
  git_rev: v{{ version }}
  git_depth: 1

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - nlohmann_json
    - spdlog
    - gtest

test:
  commands:
    - miles-cpp-test

about:
  home: https://github.com/mleszczynski-dev/miles-cpp
  license: MIT
  summary: "Experimental C++ static library with app info features"
